# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**'
    tags:
      - 'v*'


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  publishToGallery:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      uses: actions/checkout@v2
      #copy files
    - name: Build
      shell: pwsh
      run: |
        $Name = 'AiLogging'
        $Target = "$env:GITHUB_WORKSPACE\$Name"
        dir "$env:GITHUB_WORKSPACE" -recurse
        write-host "Building in: $env:GITHUB_WORKSPACE\$Name"
        New-Item -Path  "$env:GITHUB_WORKSPACE" -Name $Name -ItemType Directory -Force | Out-Null
        New-Item -Path  "$env:GITHUB_WORKSPACE" -Name Assets -ItemType Directory -Force | Out-Null
        Copy-Item -Path "$env:GITHUB_WORKSPACE\$Name`.psd1" -Destination "$Target\" -Force
        Copy-Item -Path "$env:GITHUB_WORKSPACE\$Name`.psm1" -Destination "$Target\" -Force
        Copy-Item -Path "$env:GITHUB_WORKSPACE\images" -Destination "$Target\" -Force -Recurse
        Copy-Item -Path "$env:GITHUB_WORKSPACE\lib" -Destination "$Target\" -Force -Recurse
        Copy-Item -Path "$env:GITHUB_WORKSPACE\LICENSE" -Destination "$Target\" -Force

      # Publish to PS Gallery
    - name: Publish
      shell: pwsh
      env:
        SECRET: ${{ secrets.PSGallery_APIKey }}
      run: |
        $Name = 'AiLogging'
        $Target = "$env:GITHUB_WORKSPACE\$Name"
        write-host "Publishing from: $Target"
        Get-Item -Path env:* | Out-String | Write-host
        try
        {
          if($null -ne $target)
          {
            #Publish-Module -Path $target -NuGetApiKey "$env:SECRET"
          }
        }
        catch
        {
          Write-Host "Error: $($_.Exception)"
          throw
        }
      
      #Create a release
    - name: Create Release
      id: create_release
      uses: meeDamian/github-release@2.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: Release ${{ github.ref }}
        draft: true
        prerelease: true
        files: AiLogging/
